services:
  ioc-knowledge-db:
    image: ghcr.io/cisco-eti/ioc-knowledge-memory-svc-db:1.0
    container_name: ioc-knowledge-db
    environment:
      POSTGRES_USER: ${IOC_KNOWLEDGE_DB_USER}
      POSTGRES_PASSWORD: ${IOC_KNOWLEDGE_DB_PASSWORD}
      POSTGRES_DB: ${IOC_KNOWLEDGE_DB:-ioc-knowledge-db}
    ports:
      - "${IOC_KNOWLEDGE_DB_PORT:-5456}:5432"
    volumes:
      - ioc_knowledge_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U ${IOC_KNOWLEDGE_DB_USER} -d ${IOC_KNOWLEDGE_DB:-ioc-knowledge-db}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  ioc-graph-db-viewer:
    image: skaiworldwide/agviewer:latest
    environment:
      DB_HOST: ioc-knowledge-db
      DB_PORT: 5432
      DB_USER: ${IOC_KNOWLEDGE_DB_USER}
      DB_PASSWORD: ${IOC_KNOWLEDGE_DB_PASSWORD}
      DB_NAME: ${IOC_KNOWLEDGE_DB:-ioc-knowledge-db}
    ports:
      - "${IOC_KNOWLEDGE_DB_GRAPH_UI_PORT:-3000}:3000"
    depends_on:
      - ioc-knowledge-db

  ioc-knowledge-memory-svc:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "9003:9003"
    environment:
      - SERVICE_NAME=ioc-knowledge-memory-svc
      - APPLICATION_VERSION=dev
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MEMORY_PROVIDER_REGISTRATION_URL=${MEMORY_PROVIDER_REGISTRATION_URL:-http://localhost:8000}
      - MEMORY_PROVIDER_ID=${MEMORY_PROVIDER_ID:-f2ffa4ad-682b-4bda-b2dd-592e39ba4da6}
      - IOC_KNOWLEDGE_DB_HOST=ioc-knowledge-db
      - IOC_KNOWLEDGE_DB=${IOC_KNOWLEDGE_DB:-ioc-knowledge-db}
      - IOC_KNOWLEDGE_DB_USER=${IOC_KNOWLEDGE_DB_USER}
      - IOC_KNOWLEDGE_DB_PASSWORD=${IOC_KNOWLEDGE_DB_PASSWORD}
      - IOC_KNOWLEDGE_DB_PORT=5432
      - EMBEDDING_VECTOR_SIZE=${EMBEDDING_VECTOR_SIZE:-384}
    restart: unless-stopped
    depends_on:
      ioc-knowledge-db:
        condition: service_healthy
      ioc-graph-db-viewer:
        condition: service_started

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ioc_knowledge_db_data:
