from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Dict, Any
import uuid

@dataclass
class Software:
  type: str
  name: str
  workspace_id: str
  config: Optional[Dict[str, Any]] = None
  id: str = field(default_factory=lambda: str(uuid.uuid4())) #autogenerated in db
  created_at: datetime = field(default_factory=datetime.now) #autogenerated in db
  updated_at: Optional[datetime] = None #autogenerated in db
  deleted_at: Optional[datetime] = None #soft delete
