services:
  neo4j:
    image: neo4j:5.26-community
    container_name: neo4j-graph-db
    ports:
      - "${NEO4J_PORT_HTTP:-7474}:7474"  # HTTP (UI)
      - "${NEO4J_PORT:-7687}:7687"  # Bolt (driver)
    environment:
      - NEO4J_initial_dbms_default__database=tkf
      - NEO4J_AUTH=none
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=512m # increase as required
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs: