services:
  tkf-relational-db:
    image: timescale/timescaledb-ha:pg17
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tkf}
      POSTGRES_USER: ${POSTGRES_USER:-postgresUser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgresPW}
    ports:
      - "${POSTGRES_PORT:-5455}:5432"
    volumes:
      - timescaledb_data:/var/lib/timescaledb/data

volumes:
  timescaledb_data:
